### ISSUE TITLE
Serving size preview in search (from @britton-jb)

### ISSUE THREAD

**Issue by mattcantstop** [spoonme-kitchen/spoonme-public#10]
@britton-jb had this feedback: 

> The search box for adding entries ought to have some indication of which item/serving size it defaults to for packaged goods.

`Example:` strawberry noosa the one I'm eating says 130 calories on the tin, and there are  4+ options that could be it, and I can't find which one it is at a glance. Creating a custom recipe had a pretty good flow though.

CC: @migarjo and @TheArrowsmith

**Comment by migarjo** [comment]
@britton-jb thanks for the feedback on this! We're still ironing out the specifics on exactly how we're going to address this. One thing to point out is that for Noosa Strawberry Yoghurt is that all of the duplicates you saw were actually duplicates that weren't directly related to amounts. These differences are due to trivial variations in branding. We're looking to find a way to show a clean number of results but also allow you to select food quantities with as few clicks as possible.

I'll close this for now, but if you have any other comments, please feel free to reopen this issue or open a new one.
