### ISSUE TITLE
Remove step in process to add recipe to journal

### ISSUE THREAD

**Issue by colecrawford23** [spoonme-kitchen/spoonme-public#5]
In the journal, I go to add my recipe "Simple Frittata" I click add and am taken to the page that has the list of ingredients. Since I made this recipe I would prefer to skip this step and have this automatically added.

**Comment by mattcantstop** [comment]
> Since I made this recipe I would prefer to skip this step and have this automatically added.

@colecrawford23, our reasoning behind this was that sometimes you may make the recipe, but have different ingredients on hand. Instead of having to make another recipe to track eating this meal for a few meals (if you were meal prepping) you could instead just delete that ingredient, or add more of others, while tracking. But we should have a way to immediately track it at default levels, and another way to adjust the ingredients during that meal easily. 

CC: @TheArrowsmith 

We could potentially have the `+` button automatically add it, and if you click on another spot it brings you to a spot where you can adjust the ingredients. But the quick add should be there.

**Comment by migarjo** [comment]
@colecrawford23, thanks for the feedback! I've added this to a tracking issue to discuss in the future, so I'm closing this for now. If you'd like to discuss this further, please feel free to reopen this issue!
